GET http://localhost:7000/products

###

POST http://localhost:7000/products/admin
Content-Type: application/json

{
  "product_name": "Chocolate Cup Cake",
  "product_price": "3200",
  "product_detail": "촉촉한 초코 컵케익",
  "product_image": "img/super-moist-chocolate-cupcakes-524176-1.jpg"
}

###

PUT http://localhost:7000/products/admin/100
Content-Type: application/json

{
  "product_name": "Chocolate Cup Cake",
  "product_price": "2800",
  "product_detail": "촉촉한 초코 컵케익",
  "product_image": "img/super-moist-chocolate-cupcakes-524176-1.jpg"
}

###

DELETE http://localhost:7000/products/admin/55

###

POST http://localhost:7000/users/signup
Content-Type: application/json

{
    "email": "pear@baker.com",
    "password": "password1234",
    "confirm": "password1234"
}

###
# 일반 회원 로그인
POST http://localhost:7000/users/login
Content-Type: application/json

{
    "email": "pear@baker.com",
    "password": "password1234"
}

###
# 관리자 로그인
POST http://localhost:7000/users/login
Content-Type: application/json

{
    "email": "edvocao74@gmail.com",
    "password": "1234"
}

###

GET http://localhost:7000/orders/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE2NzU2NzA1MjcsImV4cCI6MTY3NTY3NDEyN30._IE6CljsbSYev_J47bpLRpimqITqOApkUOr2_-_7yrY


###
GET http://localhost:7000/users/admin

###

GET http://localhost:7000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJpYXQiOjE2NzU2Nzc5NjAsImV4cCI6MTY3NTY4MTU2MH0.K3RjsEttDlt1wgfGeNx2tcR_iv957lpEm-Ev5qaOVRY

###