GET http://localhost:7000/products

###

POST http://localhost:7000/products/admin
Content-Type: application/json

{
  "product_name": "Chocolate Cup Cake",
  "product_price": "3200",
  "product_detail": "촉촉한 초코 컵케익",
  "product_image": "public/img/super-moist-chocolate-cupcakes-524176-1.jpg"
}

###

PUT http://localhost:7000/products/admin/10
Content-Type: application/json

{
  "product_name": "Chocolate Cup Cake",
  "product_price": "2800",
  "product_detail": "촉촉한 초코 컵케익",
  "product_image": "public/img/super-moist-chocolate-cupcakes-524176-1.jpg"
}

###

DELETE http://localhost:7000/products/admin/9

###

POST http://localhost:7000/signup
Content-Type: application/json

{
    "email": "pear@baker.com",
    "password": "password1234",
    "confirm": "password1234"
}

###

POST http://localhost:7000/login
Content-Type: application/json

{
    "email": "pear@baker.com",
    "password": "password1234"
}

###
